### ISSUE TITLE
恳求稍微详细连贯一些的部署方式

### ISSUE THREAD

**Issue by woOzZ1** [JAVClub/core#7]
试了许多次都失败了，数据库需要单独安装吗，是mysql嘛

**Comment by LoliLin** [comment]
部署 core 之前请先确定已经部署完 fetcher 了, 不然就算 core 运行起来也不会有数据

数据库是 MySQL, 要求 5.7 及以上

如果依然无法完成可以等待近期 Docker 编排出来使用 Docker 部署

**Comment by Co2333** [comment]
我目前写了个Dockerfile把fetcher和core都给打包进去了 还不太完善
打算过几天整整有没有pr给你交一份

还有这边我是推荐docker-compose的不论维护还是构建都会方便很多
除此之外还可以整一个phpmyadmin进去管理数据库 这样的话我们可以制作一份初始数据库表单以便用户直接导入设置 ~~对于我Google了半天USE SELECT SHOW的菜鸡会比较友好~~

```
# From ubuntu, we build our system
FROM ubuntu

# Depends
FROM node as node
FROM rclone/rclone as rclone
FROM linuxserver/ffmpeg as ffmpeg
FROM linuxserver/qbittorrent as qbit
#     environment:
#       - PUID=1000
#       - PGID=1000
#       - TZ=Europe/London
#       - UMASK_SET=022
#       - WEBUI_PORT=8080
#     volumes:
#       - /path/to/appdata/config:/config
#       - /path/to/downloads:/downloads
#     ports:
#       - 6881:6881
#       - 6881:6881/udp
#       - 8080:8080

COPY --from=node / /
COPY --from=rclone/rclone / /
COPY --from=linuxserver/ffmpeg / /
COPY --from=linuxserver/qbittorrent / /

# just in case
RUN mkdir -p /opt &> /dev/null

# do config setup...
RUN cd /opt && git clone https://github.com/JAVClub/core.git ./core --depth=1
RUN cd /opt/core && npm i
RUN cd /opt/core && mv config defaultconfigs

RUN cd /opt && git clone https://github.com/JAVClub/fetcher.git ./fetcher --depth=1
RUN cd /opt/fetcher && npm i

# ports things
EXPOSE 3000

# boostrap scripts
RUN printf "#!/bin/bash\n" > /bootstrap.sh
RUN printf "FILE=/opt/core/config/dev.json\nif [ -f \"\$FILE\" ]; then\n    echo \"$FILE already exist\"\nelse\n    echo \"\$FILE does not exist\"\n    mkdir -p /opt/core/config && cp /opt/core/defaultconfigs/dev.example.json /opt/core/config/dev.json\nfi\n" >> /bootstrap.sh
RUN printf "cd /opt/core && NODE_ENV=dev node src/app.js &\n" >> /bootstrap.sh
RUN printf "wait < <(jobs -p)\n" >> /bootstrap.sh

RUN chmod +x /bootstrap.sh

# Starting up....
CMD ["/bootstrap.sh"]
```

```
  
version: '3.2'

services:

  app:
    build: dockerbuild
    ports:
      - 3000:3000
    volumes: 
      - ./mnt/app/config:/opt/core/config
    links: 
      - database

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: A8635AE6-9C11-4BFF-8FC4-1A58DC105A73
    ports: 
      - 3001:80
    links:
      - database:database

  database:
    image: linuxserver/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=A8635AE6-9C11-4BFF-8FC4-1A58DC105A73
      - MYSQL_DATABASE=javclub
      - MYSQL_USER=javclub
      - MYSQL_PASSWORD=javclub-1A58DC105A73
    volumes:
      - ./mnt/database/config:/config
    restart: unless-stopped
```
